/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.phanquyen;

import com.mycompany.entities.MatHang;
import com.mycompany.repository.ProductService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hophu
 */
public class ListMatHang extends javax.swing.JFrame {

    /**
     * Creates new form ListMatHang
     */
    private String currentId = "";

    public String getCurrentId() {
        return currentId;
    }

    public void setCurrentId(String currentId) {
        this.currentId = currentId;
    }
    
    private ProductService productService;

    public ListMatHang() {
        initComponents();
        FillMatHang();
        FillCmbLoaiHang();
        FillDonViTinh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableProduct = new javax.swing.JTable();
        jLabel_loaimathang = new javax.swing.JLabel();
        jLabel_mamathang = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_dvt = new javax.swing.JLabel();
        jLabel_mota = new javax.swing.JLabel();
        cmb_loaiMatHang = new javax.swing.JComboBox<>();
        txt_matHang = new javax.swing.JTextField();
        txt_maMatHang = new javax.swing.JTextField();
        cmb_dvt = new javax.swing.JComboBox<>();
        jScrollPane_description = new javax.swing.JScrollPane();
        jTextArea_desciption = new javax.swing.JTextArea();
        txt_price = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        addSelection = new javax.swing.JMenu();
        editSelection = new javax.swing.JMenu();
        delSelection = new javax.swing.JMenu();
        UserForm = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Chọn", "Nhóm Mặt Hàng", "Mã Mặt Hàng", "Mặt Hàng", "Giá Bán", "DVT", "Mô Tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProduct);

        jLabel_loaimathang.setText("Loại Mặt Hàng");

        jLabel_mamathang.setText("Mã Mặt Hàng");

        jLabel_price.setText("Giá Bán");

        jLabel_name.setText("Mặt Hàng");

        jLabel_dvt.setText("DVT");

        jLabel_mota.setText("Mô Tả");

        jTextArea_desciption.setColumns(20);
        jTextArea_desciption.setRows(5);
        jScrollPane_description.setViewportView(jTextArea_desciption);

        addSelection.setText("Thêm");
        addSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSelectionMouseClicked(evt);
            }
        });
        jMenuBar1.add(addSelection);

        editSelection.setText("Sửa");
        editSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSelectionMouseClicked(evt);
            }
        });
        jMenuBar1.add(editSelection);

        delSelection.setText("Xóa");
        delSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delSelectionMouseClicked(evt);
            }
        });
        jMenuBar1.add(delSelection);

        UserForm.setText("Quản Lý Nhân Sự");
        UserForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserFormMouseClicked(evt);
            }
        });
        jMenuBar1.add(UserForm);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_mamathang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_loaimathang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_price, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_loaiMatHang, 0, 117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_price)
                            .addComponent(txt_maMatHang))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_matHang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_mota, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmb_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane_description, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_loaimathang)
                            .addComponent(jLabel_name)
                            .addComponent(jLabel_mota)
                            .addComponent(cmb_loaiMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_mamathang)
                            .addComponent(jLabel_dvt)
                            .addComponent(txt_maMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_price)))
                    .addComponent(jScrollPane_description, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProductMouseClicked
        int row = TableProduct.getSelectedRow();
        TableProduct.setValueAt(!(Boolean) TableProduct.getValueAt(row, 0), row, 0);
        cmb_loaiMatHang.setSelectedItem(TableProduct.getValueAt(row, 1));
        txt_maMatHang.setText(TableProduct.getValueAt(row, 2).toString());
        txt_matHang.setText(TableProduct.getValueAt(row, 3).toString());
        txt_price.setText(TableProduct.getValueAt(row, 4).toString());
        cmb_dvt.setSelectedItem(TableProduct.getValueAt(row, 5));
        jTextArea_desciption.setText(TableProduct.getValueAt(row, 6).toString());
        currentId = TableProduct.getValueAt(row, 2).toString();
    }//GEN-LAST:event_TableProductMouseClicked

    private void addSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSelectionMouseClicked
        MatHang product = new MatHang();
        product.setMAMH(txt_maMatHang.getText());
        product.setTENMH(txt_matHang.getText());
        product.setGIABAN(Float.parseFloat(txt_price.getText()));
        product.setDVT(cmb_dvt.getSelectedItem().toString());
        product.setMALOAI(cmb_loaiMatHang.getSelectedItem().toString());
        product.setMOTA(jTextArea_desciption.getText());
        product.setVOHIEUHOA("false");
        productService.addProduct(product);
        FillMatHang();
    }//GEN-LAST:event_addSelectionMouseClicked

    private void editSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSelectionMouseClicked
        try {
            MatHang product = new MatHang();
            product.setMAMH(txt_maMatHang.getText());
            product.setTENMH(txt_matHang.getText());
            product.setGIABAN(Float.parseFloat(txt_price.getText()));
            product.setDVT(cmb_dvt.getSelectedItem().toString());
            product.setMALOAI(cmb_loaiMatHang.getSelectedItem().toString());
            product.setMOTA(jTextArea_desciption.getText());
            product.setVOHIEUHOA("false");
            productService.updateProduct(product, currentId);
            FillMatHang();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sửa thất bại!!! ", "failed",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editSelectionMouseClicked

    private void delSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delSelectionMouseClicked
        if (productService.getProductById(txt_maMatHang.getText()) != null) {
            productService.deleteProduct(txt_maMatHang.getText());
            FillMatHang();
        } else {
            JOptionPane.showMessageDialog(null, "Xóa thất bại!!! ", "failed",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_delSelectionMouseClicked

    private void UserFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserFormMouseClicked
        PhanQuyenUser a = new PhanQuyenUser();
        a.setTitle(this.getTitle());
        this.setVisible(false);
        a.show();
    }//GEN-LAST:event_UserFormMouseClicked

    private void FillMatHang() {
        productService = new ProductService();
        List<MatHang> productList = productService.getAll();
        DefaultTableModel model = (DefaultTableModel) TableProduct.getModel();
        model.setRowCount(0);
        for (MatHang mathang : productList) {
            Object[] row = {false, mathang.getMALOAI(), mathang.getMAMH(), mathang.getTENMH(), mathang.getGIABAN(), mathang.getDVT(), mathang.getMOTA()};
            model.addRow(row);
        }
    }

    private void FillCmbLoaiHang() {
        productService = new ProductService();
        List<MatHang> productList = productService.getAll();
        List<String> LoaiMatHang = new ArrayList<>();
        for (var item : productList) {
            if (!LoaiMatHang.contains(item.getMALOAI())) {
                LoaiMatHang.add(item.getMALOAI());
            }
        }
        for (var item : LoaiMatHang) {
            cmb_loaiMatHang.addItem(item);
        }
    }

    private void FillDonViTinh() {
        productService = new ProductService();
        List<MatHang> productList = productService.getAll();
        List<String> donViTinh = new ArrayList<>();
        for (var item : productList) {
            if (!donViTinh.contains(item.getDVT())) {
                donViTinh.add(item.getDVT());
            }
        }
        for (var item : donViTinh) {
            cmb_dvt.addItem(item);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListMatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListMatHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProduct;
    private javax.swing.JMenu UserForm;
    private javax.swing.JMenu addSelection;
    private javax.swing.JComboBox<String> cmb_dvt;
    private javax.swing.JComboBox<String> cmb_loaiMatHang;
    private javax.swing.JMenu delSelection;
    private javax.swing.JMenu editSelection;
    private javax.swing.JLabel jLabel_dvt;
    private javax.swing.JLabel jLabel_loaimathang;
    private javax.swing.JLabel jLabel_mamathang;
    private javax.swing.JLabel jLabel_mota;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_description;
    private javax.swing.JTextArea jTextArea_desciption;
    private javax.swing.JTextField txt_maMatHang;
    private javax.swing.JTextField txt_matHang;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
